# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: "3.7"

services:
  demoproxy:
    #cannot scale a service beyond 1 container refer to https://docs.docker.com/compose/compose-file/#container_name
    container_name: demoproxy
    build:
      context: .
      dockerfile: DemoProxy/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    
  demoaddressapi:
    #cannot scale a service beyond 1 container refer to https://docs.docker.com/compose/compose-file/#container_name
    container_name: addressesapi
    build:
      context: .
      dockerfile: DemoAddressApi/Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    
  demoitemsapi:
    #cannot scale a service beyond 1 container refer to https://docs.docker.com/compose/compose-file/#container_name
    container_name: demoitemsapi
    build:
      context: .
      dockerfile: DemoItemsApi/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  
networks:
  default:
    name: demo-proxy-network
    driver: bridge
