### Cluters
GET http://0.0.0.0:5000/yarp/clusters
Accept: application/json

### Routes
GET http://0.0.0.0:5000/yarp/incoming
Accept: application/json

### Proxied Items
GET http://0.0.0.0:5000/api/items
Accept: application/json
Host: items

###